language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: wJ6DaDpD9hRXHsyjzQs041oFu7gugb411yQVMHR6xPxE5j11aSOFhyf0QMKo9iKFWyvYMKkZ4ZA3WLKYmM4U589sVH/SbzjlI80TvAR6iKIUxlUpqkdVLWETcfYudN74322QkysHLm6Ox/EMeb4nhN6z2dPBJMkaJu/o5SeBu3b14x5/Tby7xrz1lY/T3o0wRSiBsRZyhtzVr/GQu4IOHFQPZKULRcbGQpXKoQI1pGnJX99z97lsKKoqhN94vGxwT8R0aurRm5JdWL1+ChYTlj7XKS5+jUDEaTzIrrYZl+XFISNj687CLaurQB1cyFnIFxS+t7SgKhR0uIRhqRyECowDs3vslBNIRe2OudlhR4RD0yZy+uzyLOe5AmN9NmaRiHZRKZPPYrU8HxbehjwuCv3gRKEJNlEM7g3ZBURRfbAQcx5HYi6towQ5r7YetakjiZl+pYhFoEzI1bz8sXHWoDY6xfIALIyUteFJ8qyktlxUK0RYY2WquR2C38Xjxu64JwYuG9sQMiILiwitKyBE4NpV7yZVg5R/9W4TtcFkA8Rhw8QoeaEE6wg/G8dyirByLcB89FbcKBirCiUebl3uBRllB4gKyeSyFcur4hyIo85YwqaUP9Ujl5CoF30whpG3ngGO7d1xpXDOuYsuhc9bOcGNXcvGLJaepvmjMXve8TM=
        on_pull_requests: false
