language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: 0erpniRKMOkC7xP4QUkyt5nN0rSBCYTW+N2cInvN3YGlHyl1lqPhmCV9e6yWLd0ie+22rpd9DKsqJd61BHMnc/jSTuhi0oLDzQFpA8coRdDu6lUxaBdgnqYedbKC18+3wKpx5rxzzcj2OZTPQXCuoqI0XNMMJc7sf3ICTSL15/rjQ+kApO3cRLHjrDPFcxCs4HnRYzBJVmp++42Cvi3VK+pnZLm2nZ2wZhAreH7pvnlIu+O7KqwvSquOVl+i0J76ExY7x9VgZp9+NmNSIFg0jCI7slZPo4Pb1GC4dw/OtgZkjiganl6VpK71NHVgo6x+igN3kOmjomNVAjjBLOoC+phQZ7CyTQClo8yC6O3x8GsFEzn9KlFSs5Rv826LVklGzAt9GuxbvXekU/9PioVrvS8iAwZKH+2vkwK6h1JldUlpw6DINe51j+X9sdyRWiX4UcBTfgXfIyMCErM0krTF9TpFzZwDl1HtXHr7RapPRdBL1RWvDhCD5uyorlISw+Ih2jDZGl2eQYTCp0lSk3UxhGebe07OJXcg02D0/uDrDzDoCjEAdryc73oFqzMvI+PV64FF3fiSblpijl4/8k5GvzhTwZf7r7UJc8H6rK7JpiR8gOeLjpVM/GKzdXG0uz12yhBWFyIxNrogRsHGkm5cznouxWp5QdTqLoziB/iYoyY=
        on_pull_requests: false
