version: '3.5'
services:
    postgres:
        image: postgres:11
        container_name: geofences_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=geofences
        ports:
            - '5432:5432'
        networks:
            - geofences
        volumes:
            - postgres:/data/db
    # redis:
    #     image: redis
    #     container_name: geofences_redis
    #     ports:
    #         - "6379:6379"
    #     networks:
    #         - geofences
    #     volumes:
    #         - redis:/data

networks:
    geofences:
        name: geofences-network
        internal: true

volumes:
    postgres:
        driver: local
